// Generated by gencpp from file mbot_catching/EnvStatistic.msg
// DO NOT EDIT!


#ifndef MBOT_CATCHING_MESSAGE_ENVSTATISTIC_H
#define MBOT_CATCHING_MESSAGE_ENVSTATISTIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mbot_catching
{
template <class ContainerAllocator>
struct EnvStatistic_
{
  typedef EnvStatistic_<ContainerAllocator> Type;

  EnvStatistic_()
    : header()
    , action()
    , reward(0.0)  {
    }
  EnvStatistic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , action(_alloc)
    , reward(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _action_type;
  _action_type action;

   typedef float _reward_type;
  _reward_type reward;





  typedef boost::shared_ptr< ::mbot_catching::EnvStatistic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mbot_catching::EnvStatistic_<ContainerAllocator> const> ConstPtr;

}; // struct EnvStatistic_

typedef ::mbot_catching::EnvStatistic_<std::allocator<void> > EnvStatistic;

typedef boost::shared_ptr< ::mbot_catching::EnvStatistic > EnvStatisticPtr;
typedef boost::shared_ptr< ::mbot_catching::EnvStatistic const> EnvStatisticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mbot_catching::EnvStatistic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mbot_catching::EnvStatistic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mbot_catching::EnvStatistic_<ContainerAllocator1> & lhs, const ::mbot_catching::EnvStatistic_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.action == rhs.action &&
    lhs.reward == rhs.reward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mbot_catching::EnvStatistic_<ContainerAllocator1> & lhs, const ::mbot_catching::EnvStatistic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mbot_catching

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mbot_catching::EnvStatistic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mbot_catching::EnvStatistic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mbot_catching::EnvStatistic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae95a53e3cd6840f18df4e5cfcb7004c";
  }

  static const char* value(const ::mbot_catching::EnvStatistic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae95a53e3cd6840fULL;
  static const uint64_t static_value2 = 0x18df4e5cfcb7004cULL;
};

template<class ContainerAllocator>
struct DataType< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mbot_catching/EnvStatistic";
  }

  static const char* value(const ::mbot_catching::EnvStatistic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32[] action\n"
"float32 reward\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mbot_catching::EnvStatistic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.action);
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnvStatistic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mbot_catching::EnvStatistic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mbot_catching::EnvStatistic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action[i]);
    }
    s << indent << "reward: ";
    Printer<float>::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MBOT_CATCHING_MESSAGE_ENVSTATISTIC_H
